# Generated by Django 4.2.2 on 2023-06-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
    ]
