# Generated by Django 4.2.2 on 2023-06-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReactAdmin', '0002_alter_respondent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='date',
        ),
    ]
