# Generated by Django 4.2.2 on 2023-06-28 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactAdmin', '0003_remove_respondent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='date',
            field=models.CharField(default=datetime.datetime(2023, 6, 28, 18, 51, 53, 405346, tzinfo=datetime.timezone.utc), max_length=240),
            preserve_default=False,
        ),
    ]
