# Generated by Django 4.2.2 on 2023-06-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactAdmin', '0004_respondent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('audience_age', models.CharField(max_length=240)),
                ('desc', models.CharField(max_length=500)),
                ('questions', models.TextField()),
            ],
        ),
    ]
