# Generated by Django 4.2.2 on 2023-07-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactAdmin', '0006_project_status_project_total_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(default='AIzaSyClzfrOzB818x55FASHvX4JuGQciR9lv7q', max_length=500),
            preserve_default=False,
        ),
    ]
