# Generated by Django 4.2.2 on 2023-08-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactAdmin', '0008_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_respondent',
            field=models.IntegerField(default=0),
        ),
    ]
